GENERIC_SEMANTIC: str = 'Generic / Unmapped'
DATE_CALENDAR_SEMANTIC: str = 'Date / Calendar'
IDENTIFIER_SEMANTIC: str = 'Identifier (ID)'
FREE_FORM_TEXT_SEMANTIC: str = 'Free-form Text'
PERSON_NAME_SEMANTIC: str = 'Person Name / Identifier'


ENTITY_LABEL_SEMANTIC: str = 'Entity Label / Name'


CATEGORY_SEMANTIC: str = 'Category / Classification'


DEFAULT_FUZZY_THRESHOLD: float = 0.85
SHORT_FUZZY_THRESHOLD: float = 0.95


STRONG_CATEGORIES: dict[str, list[str]] = {
    IDENTIFIER_SEMANTIC: [
        "id",
        "cod",
        "codigo",
        "code",
        "key",
        "number",
        "matricula",
        "mat",
        "cpf",
        "cnpj",
        "registro",
        "chave",
        "identifier",
        "iden",
        "nr",
        "num",
        "pk",
        "fk",
        "sequencial",
    ],
    DATE_CALENDAR_SEMANTIC: [
        "date",
        "dt",
        "data",
        "time",
        "timestamp",
        "periodo",
        "competencia",
        "admissao",
        "demissao",
        "nascimento",
        "vencimento",
        "inicio",
        "fim",
        "prazo",
        "realizacao",
        "referencia",
        "vigencia",
        "expiracao",
        "ano",
    ],
    'Status / Indicator / Flag': [
        "status",
        "flg",
        "flag",
        "is",
        "has",
        "state",
        "situacao",
        "enforced",
        "ativo",
        "inativo",
        "habilitado",
        "bloqueado",
    ],
    'Financial Value': [
        "salario",
        "salary",
        "wage",
        "remuneracao",
        "vlr",
        "valor",
        "custo",
        "cost",
        "preco",
        "price",
        "receita",
        "revenue",
        "despesa",
        "expense",
        "budget",
        "orcamento",
        "bonus",
        "comissao",
        "honorario",
        "verba",
        "provisao",
        "encargo",
    ],
    'Quantity / Metric': [
        "qtd",
        "quantidade",
        "count",
        "total",
        "volume",
        "horas",
        "dias",
        "carga",
        "duracao",
        "frequencia",
        "score",
        "nota",
        "percentual",
        "pct",
        "indice",
        "taxa",
        "ratio",
        "proporcao",
        "media",
    ],
    'Free-form Text': [
        "desc",
        "descricao",
        "description",
        "obs",
        "observacao",
        "comentario",
        "justificativa",
        "detalhe",
        "motivo",
        "complemento",
        "historico",
        "task",
        "function",
        "resumo",
        "anotacao",
        "mensagem",
    ],
    'Person Name / Identifier': [
        "nome",
        "name",
        "colaborador",
        "funcionario",
        "empregado",
        "pessoa",
        "participante",
        "aluno",
        "candidato",
        "usuario",
        "user",
    ],
    'Contact / Network': [
        "email",
        "mail",
        "telefone",
        "celular",
        "ramal",
        "whatsapp",
        "contato",
        "fone",
        "phone",
    ],
    'Assessment Result': [
        "resultado",
        "result",
        "aprovacao",
        "reprovacao",
        "conceito",
        "avaliacao",
        "desempenho",
        "conclusao",
        "outcome",
        "performance",
        "feedback",
        "rating",
        "classificacao",
    ],
}


FUZZY_CATEGORIES: dict[str, list[str]] = {
    'Geographic Location': [
        "country",
        "province",
        "city",
        "facility",
        "pais",
        "cidade",
        "estado",
        "regiao",
        "municipio",
        "cep",
        "uf",
        "endereco",
        "local",
        "latitude",
        "longitude",
        "bairro",
        "logradouro",
    ],
    'Organizational Structure': [
        "department",
        "company",
        "business",
        "hierarquia",
        "departamento",
        "diretoria",
        "gerencia",
        "setor",
        "area",
        "divisao",
        "celula",
        "squad",
        "lotacao",
        "unidade",
        "filial",
        "subsidiaria",
        "agencia",
        "coordenacao",
        "superintendencia",
        "nucleo",
        "equipe",
        "time",
        "orgao",
        "secretaria",
        "ministerio",
        "autarquia",
    ],
    'Electoral Process': [
        "eleicao",
        "partido",
        "pleito",
        "coligacao",
        "chapa",
        "urna",
        "votacao",
        "sufragio",
        "candidatura",
    ],
    'Workforce Profile': [
        "gender",
        "nationality",
        "career",
        "workforce",
        "staff",
        "genero",
        "nacionalidade",
        "idade",
        "raca",
        "escolaridade",
        "deficiencia",
        "etnia",
    ],
    'Product / Item': [
        "product",
        "item",
        "sku",
        "merchandise",
        "produto",
        "mercadoria",
        "insumo",
        "material",
        "ativo",
        "equipamento",
        "veiculo",
        "artigo",
        "marca",
        "brand",
        "modelo",
        "model",
    ],
    'Job / Function': [
        "cargo",
        "funcao",
        "nivel",
        "grade",
        "posicao",
        "categoria",
        "classe",
        "faixa",
        "perfil",
        "role",
        "position",
        "job",
        "title",
        "occupation",
    ],
    'Finance / Cost': [
        "custo",
        "cost",
        "centro de custo",
        "despesa",
        "orcamento",
        "budget",
        "financeiro",
        "finance",
        "contabil",
        "fiscal",
        "conta",
        "rateio",
    ],
    'Course / Training': [
        "curso",
        "treinamento",
        "capacitacao",
        "formacao",
        "modulo",
        "trilha",
        "programa",
        "workshop",
        "disciplina",
        "tema",
        "course",
        "training",
        "learning",
        "certificacao",
    ],
}


QUALIFIER_TOKENS: frozenset[str] = frozenset(
    {
        "id",
        "cod",
        "codigo",
        "code",
        "key",
        "chave",
        "pk",
        "fk",
        "nr",
        "num",
        "number",
        "matricula",
        "mat",
        "iden",
        "identifier",
        "registro",
        "nome",
        "name",
        "desc",
        "descricao",
        "description",
        "sigla",
        "abrev",
        "tipo",
        "type",
        "categoria",
        "class",
        "flag",
        "flg",
        "status",
        "qtd",
        "quantidade",
        "total",
        "vlr",
        "valor",
        "pct",
        "percentual",
        "dt",
        "date",
        "data",
        "hora",
        "time",
        "timestamp",
        "dias",
        "sequencial",
    }
)


QUALIFIER_TOKEN_WEIGHT: float = 0.45
ENTITY_TOKEN_WEIGHT: float = 1.0


PERSON_DOMAINS: frozenset[str] = frozenset({'Workforce Profile'})


MAX_CATEGORY_CARDINALITY: int = 100
