from typing import Any

from . import _taxonomy as config

ABBREVIATIONS: dict[str, list[str]] = {
    "cd": ["codigo"],
    "cod": ["codigo"],
    "cdg": ["codigo"],
    "dt": ["data"],
    "dta": ["data"],
    "hr": ["hora"],
    "vl": ["valor"],
    "vlr": ["valor"],
    "val": ["valor"],
    "qt": ["quantidade"],
    "qtd": ["quantidade"],
    "qtde": ["quantidade"],
    "nr": ["numero"],
    "num": ["numero"],
    "nro": ["numero"],
    "nm": ["nome"],
    "ds": ["descricao"],
    "dsc": ["descricao"],
    "desc": ["descricao"],
    "tp": ["tipo"],
    "fl": ["flag"],
    "flg": ["flag"],
    "sg": ["sigla"],
    "pc": ["percentual"],
    "perc": ["percentual"],
    "pct": ["percentual"],
    "id": ["identificador"],
    "seq": ["sequencial"],
    "sq": ["sequencial"],
    "st": ["status"],
    "ind": ["indicador"],
    "mt": ["matricula"],
    "mat": ["matricula"],
    "dep": ["departamento", "dependente", "deposito"],
    "dpto": ["departamento"],
    "depto": ["departamento"],
    "dept": ["departamento"],
    "lot": ["lotacao"],
    "lotac": ["lotacao"],
    "func": ["funcionario"],
    "fnc": ["funcionario"],
    "colab": ["colaborador"],
    "emp": ["empresa", "empregado"],
    "empr": ["empresa"],
    "cargo": ["cargo"],
    "cgo": ["cargo"],
    "fun": ["funcao"],
    "adm": ["admissao"],
    "dem": ["demissao"],
    "nasc": ["nascimento"],
    "sal": ["salario"],
    "rem": ["remuneracao"],
    "benef": ["beneficio"],
    "ferias": ["ferias"],
    "afast": ["afastamento"],
    "desl": ["desligamento"],
    "sit": ["situacao"],
    "escol": ["escolaridade"],
    "esc": ["escolaridade"],
    "mvto": ["movimento"],
    "mov": ["movimento"],
    "movto": ["movimento"],
    "cli": ["cliente"],
    "clnt": ["cliente"],
    "forn": ["fornecedor"],
    "prod": ["produto"],
    "prd": ["produto"],
    "ped": ["pedido"],
    "nf": ["nota"],
    "ctr": ["contrato"],
    "ctt": ["contato"],
    "mun": ["municipio"],
    "cid": ["cidade"],
    "est": ["estado"],
    "ender": ["endereco"],
    "end": ["endereco"],
    "bai": ["bairro"],
    "reg": ["regiao"],
    "fil": ["filial"],
    "uni": ["unidade"],
    "ini": ["inicio"],
    "fim": ["fim"],
    "venc": ["vencimento"],
    "ref": ["referencia"],
    "comp": ["competencia"],
    "vig": ["vigencia"],
    "cad": ["cadastro"],
    "hist": ["historico"],
    "obs": ["observacao"],
    "resp": ["responsavel"],
    "tot": ["total"],
    "liq": ["liquido"],
    "brt": ["bruto"],
    "med": ["media"],
    "acum": ["acumulado"],
    "curs": ["curso"],
    "trein": ["treinamento"],
    "cap": ["capacitacao"],
    "aval": ["avaliacao"],
    "res": ["resultado"],
    "nota": ["nota"],
}


_UFS = {
    "ac",
    "al",
    "ap",
    "am",
    "ba",
    "ce",
    "df",
    "es",
    "go",
    "ma",
    "mt",
    "ms",
    "mg",
    "pa",
    "pb",
    "pr",
    "pe",
    "pi",
    "rj",
    "rn",
    "rs",
    "ro",
    "rr",
    "sc",
    "sp",
    "se",
    "to",
}

_CAPITAIS = {
    "rio branco",
    "maceio",
    "macapa",
    "manaus",
    "salvador",
    "fortaleza",
    "brasilia",
    "vitoria",
    "goiania",
    "sao luis",
    "cuiaba",
    "campo grande",
    "belo horizonte",
    "belem",
    "joao pessoa",
    "curitiba",
    "recife",
    "teresina",
    "rio de janeiro",
    "natal",
    "porto alegre",
    "porto velho",
    "boa vista",
    "florianopolis",
    "sao paulo",
    "aracaju",
    "palmas",
}

_REGIOES = {"norte", "nordeste", "centro-oeste", "centro oeste", "sudeste", "sul"}

_SEXO = {
    "m",
    "f",
    "masculino",
    "feminino",
    "homem",
    "mulher",
    "male",
    "female",
    "outro",
    "nao binario",
    "prefiro nao informar",
}

_BOOLEANOS = {
    "s",
    "n",
    "sim",
    "nao",
    "true",
    "false",
    "verdadeiro",
    "falso",
    "v",
    "f",
    "y",
    "yes",
    "no",
    "0",
    "1",
    "t",
}

_STATUS_ATIVIDADE = {
    "ativo",
    "inativo",
    "ativa",
    "inativa",
    "habilitado",
    "desabilitado",
    "bloqueado",
    "desbloqueado",
    "cancelado",
    "suspenso",
    "pendente",
    "aprovado",
    "reprovado",
    "em analise",
    "concluido",
    "aberto",
    "fechado",
}

_ESTADO_CIVIL = {
    "solteiro",
    "solteira",
    "casado",
    "casada",
    "divorciado",
    "divorciada",
    "viuvo",
    "viuva",
    "separado",
    "separada",
    "uniao estavel",
    "amasiado",
}

_ESCOLARIDADE = {
    "fundamental",
    "fundamental incompleto",
    "fundamental completo",
    "medio",
    "medio incompleto",
    "medio completo",
    "ensino medio",
    "superior",
    "superior incompleto",
    "superior completo",
    "graduacao",
    "pos-graduacao",
    "pos graduacao",
    "especializacao",
    "mba",
    "mestrado",
    "doutorado",
    "pos-doutorado",
    "analfabeto",
}

_MESES = {
    "janeiro",
    "fevereiro",
    "marco",
    "abril",
    "maio",
    "junho",
    "julho",
    "agosto",
    "setembro",
    "outubro",
    "novembro",
    "dezembro",
    "jan",
    "fev",
    "mar",
    "abr",
    "mai",
    "jun",
    "jul",
    "ago",
    "set",
    "out",
    "nov",
    "dez",
    "january",
    "february",
    "march",
    "april",
    "may",
    "june",
    "july",
    "august",
    "september",
    "october",
    "november",
    "december",
}

_DIAS_SEMANA = {
    "segunda",
    "terca",
    "quarta",
    "quinta",
    "sexta",
    "sabado",
    "domingo",
    "segunda-feira",
    "terca-feira",
    "quarta-feira",
    "quinta-feira",
    "sexta-feira",
    "monday",
    "tuesday",
    "wednesday",
    "thursday",
    "friday",
    "saturday",
    "sunday",
}

_MOEDAS = {"brl", "usd", "eur", "gbp", "ars", "clp", "jpy", "chf", "cad", "r$", "us$"}

_TURNOS = {"manha", "tarde", "noite", "madrugada", "integral", "comercial", "diurno", "noturno"}

_RACA_COR = {"branca", "preta", "parda", "amarela", "indigena", "nao declarada", "nao informada"}

_PORTE_CONTRATO = {
    "clt",
    "pj",
    "estagio",
    "estagiario",
    "aprendiz",
    "temporario",
    "terceirizado",
    "autonomo",
    "cooperado",
    "efetivo",
    "trainee",
    "socio",
    "diretor estatutario",
}


GAZETTEERS: list[dict[str, Any]] = [
    {
        "name": "UF brasileira",
        "values": _UFS,
        "category": 'Geographic Location',
        "axis": "domain",
        "minimum_coverage": 0.85,
        "weight": 0.95,
        "max_distinct": 30,
    },
    {
        "name": "capital brasileira",
        "values": _CAPITAIS,
        "category": 'Geographic Location',
        "axis": "domain",
        "minimum_coverage": 0.7,
        "weight": 0.9,
        "max_distinct": 40,
    },
    {
        "name": "região do Brasil",
        "values": _REGIOES,
        "category": 'Geographic Location',
        "axis": "domain",
        "minimum_coverage": 0.9,
        "weight": 0.9,
        "max_distinct": 8,
    },
    {
        "name": "sexo/gênero",
        "values": _SEXO,
        "category": 'Workforce Profile',
        "axis": "domain",
        "minimum_coverage": 0.9,
        "weight": 0.85,
        "max_distinct": 8,
    },
    {
        "name": "raça/cor (IBGE)",
        "values": _RACA_COR,
        "category": 'Workforce Profile',
        "axis": "domain",
        "minimum_coverage": 0.8,
        "weight": 0.9,
        "max_distinct": 10,
    },
    {
        "name": "estado civil",
        "values": _ESTADO_CIVIL,
        "category": 'Workforce Profile',
        "axis": "domain",
        "minimum_coverage": 0.8,
        "weight": 0.9,
        "max_distinct": 15,
    },
    {
        "name": "escolaridade",
        "values": _ESCOLARIDADE,
        "category": 'Workforce Profile',
        "axis": "domain",
        "minimum_coverage": 0.7,
        "weight": 0.9,
        "max_distinct": 25,
    },
    {
        "name": "vínculo/contrato",
        "values": _PORTE_CONTRATO,
        "category": 'Job / Function',
        "axis": "domain",
        "minimum_coverage": 0.8,
        "weight": 0.85,
        "max_distinct": 20,
    },
    {
        "name": "booleano textual",
        "values": _BOOLEANOS,
        "category": 'Status / Indicator / Flag',
        "axis": "role",
        "minimum_coverage": 1.0,
        "weight": 0.8,
        "max_distinct": 4,
    },
    {
        "name": "status de atividade",
        "values": _STATUS_ATIVIDADE,
        "category": 'Status / Indicator / Flag',
        "axis": "role",
        "minimum_coverage": 0.8,
        "weight": 0.85,
        "max_distinct": 15,
    },
    {
        "name": "mês",
        "values": _MESES,
        "category": config.DATE_CALENDAR_SEMANTIC,
        "axis": "role",
        "minimum_coverage": 0.9,
        "weight": 0.85,
        "max_distinct": 14,
    },
    {
        "name": "dia da semana",
        "values": _DIAS_SEMANA,
        "category": config.DATE_CALENDAR_SEMANTIC,
        "axis": "role",
        "minimum_coverage": 0.9,
        "weight": 0.85,
        "max_distinct": 10,
    },
    {
        "name": "moeda ISO",
        "values": _MOEDAS,
        "category": 'Financial Value',
        "axis": "role",
        "minimum_coverage": 0.9,
        "weight": 0.8,
        "max_distinct": 12,
    },
    {
        "name": "turno",
        "values": _TURNOS,
        "category": 'Job / Function',
        "axis": "domain",
        "minimum_coverage": 0.9,
        "weight": 0.75,
        "max_distinct": 10,
    },
]
